<?php
/**
 * Created by PhpStorm.
 * User: guilherme.zupolini
 * Date: 22/06/2017
 * Time: 13:17
 */

$form = $this->form;
?>

<fieldset>
    <?php echo $this->form()->openTag($form);?>
    <legend>Consultar Cursos</legend>
    <div class="row form-group">
        <div class="col-md-6 col-xs-6">
            <?php echo $this->formLabel($form->get("nmCurso"));?>
            <?php echo $this->formInput($form->get("nmCurso"));?>
        </div>
    </div>

    <div class="row form-group">
        <div class="col-md-2 col-xs-2">
            <?php echo $this->formLabel($form->get("sgCurso"));?>
            <?php echo $this->formInput($form->get("sgCurso"));?>
        </div>
    </div>

    <div class="row form-group">
        <div class="col-md-6 col-xs-6">
            <button type="button" class="btn btn-default" id="btnCadastrar">Cadastrar</button>
            <button type="button" class="btn btn-default" id="btnLimpar">Limpar</button>
            <button type="button" class="btn btn-primary" id="btnConsultar">Consultar</button>
        </div>
    </div>
    <?php echo $this->form()->closeTag();?>
</fieldset>

<table id="tabelaConsulta" style="display: none;">
    <thead>
        <tr>
            <th>Nome Curso</th>
            <th>Sigla Curso</th>
            <th>Carga horária</th>
            <th>Ações</th>
        </tr>
    </thead>
</table>

<script>
    $(document).ready(function () {
        $('#btnCadastrar').on('click', function () {
           window.location.assign('/application/index/cadastro-curso');
        });

        $('#btnLimpar').on('click', function () {
           limparCampos();
            if($.fn.dataTable.isDataTable('#tabelaConsulta')){
                $('#tabelaConsulta').DataTable().destroy();
                $('#tabelaConsulta').hide();
                $('#tabelaConsulta tbody').html("");
            }
        });

    $('#btnConsultar').on('click', function () {
        $('#tabelaConsulta').show();
            if($.fn.dataTable.isDataTable('#tabelaConsulta')){
                $('#tabelaConsulta').DataTable().destroy();
            }

                    $('#tabelaConsulta').DataTable({
                        language: {
                            paginate: {
                              previous: "Anterior",
                                next: "Próximo"
                            },
                            emptyTable: "Nenhum registro encontrado !",
                            info: "Mostrando _END_ de _MAX_ Registros",
                            loadingRecords: "Carregando...",
                            lengthMenu: 'Mostrar <select>'+
                                            '<option value="10">10</option>'+
                                            '<option value="15">15</option>'+
                                            '<option value="20">20</option>'+
                                            '<option value="30">30</option>'+
                                        '</select> registros'
                        },
                        searching: false,
                        ajax: {
                            url: "/application/index/listar-curso",
                            datatype: "JSON",
                            type: "POST",
                            data: {
                                nmCurso: $.trim($('#nmCurso').val()),
                                sgCurso: $.trim($('#sgCurso').val())
                            },
                            dataSrc: ''
                        },
                        columns: [
                            {data: "nmCurso"},
                            {data: "sgCurso"},
                            {data: "nuCargaHorario"},
                            {data: "acoes"}
                        ]
                    });

//            });
        });

        removerCurso = function (id, row) {
//            alert(row);

            var remove = confirm("Deseja realmente remover esse curso? Essa ação não pode ser desfeita");

            if(remove){

                $.ajax({
                    url: '/application/index/remover-curso',
                    datatype: 'JSON',
                    type: 'POST',
                    data: {id: id},
                    success: function (data) {
                        var retorno = JSON.parse(data);
                        $('#tabelaConsulta').DataTable().row(row.parents('tr')).remove().draw();
                        console.log(retorno);
                        voltarTopo();
                        alertMessage(retorno.msg, retorno.status, "#alertMsg");

                    }
                });
            }
        }
    })
</script>
